version: '3.7'
services:
  redis-master:
    image: redis:6
    container_name:  master
    # volumes:
    #   - "./.data:/data"
    ports:
      - "6379:6379"
 
  redis-slave:
    image: redis:6
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    # volumes:
    #   - "./.data:/data"
    ports:
      - "6380-6385:6379"
     
  # Instance 1
  redis-sentinel:
    build: 
      context: ./redis-sentinel
    container_name: sentinel
    ports:
      - "26379:26379"
    links:
      - redis-master
 
